# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  - 5.2
  # aliased to 5.3.8
  - 5.3
  # aliased to 5.4.0rc4
  - 5.4
before_script: cd tests
script: phpunit SmsTest.php